version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_USER: galibot
      DB_PASSWORD: your_secure_password
      DB_NAME: galibot
      DB_HOST: db
      DB_PORT: 5432
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: your_secure_password
      POSTGRES_DB: galibot
      POSTGRES_USER: galibot
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U galibot"]
      timeout: 20s
      retries: 10
volumes:
  db-data:
